# Generated by Django 6.1.1 on 2026-09-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_refundrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
    ]
